# Generated by Django 3.0.8 on 2020-08-16 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200816_1834'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
